---
title: "Bootstrapped: Mean Matched Max Correlations Comparison"
author: "Jacob DeRosa"
output:
  html_document:
    number_sections: no
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
      
---

```{r, echo = F, include = F}

#load libraries 
library(dplyr)
library(ggplot2)

analysis = "Mean_Match_Comparison"
sample = "CBCL"

analysis_name <- paste0(sample, '/', analysis)
todays_date <- Sys.Date()

dir.create(paste0('C:/Users/jacob.derosa/Desktop/Scripts/Baggin_Subtyping/CBCL/plots/',sample,'/',analysis))

```

```{r}

boot_matched =read.csv("C:/Users/jacob.derosa/Desktop/Scripts/Baggin_Subtyping/boot_matched.csv", header = T, sep=",")[-1] 
boot_matched$Group = "Bootrapped"

non_boot_matched =read.csv("C:/Users/jacob.derosa/Desktop/Scripts/Baggin_Subtyping/nonboot_matched.csv", header = T, sep=",")[-1] 
non_boot_matched$Group = "Non-Bootstrapped"

matched = rbind(non_boot_matched, boot_matched)

#plot max correlations confidence intervals 
ggplot(data = matched, aes(x = X, y = meanX1, group = Group)) +
  geom_errorbar(aes(ymin = X1Lwr95, ymax = X1Upr95), alpha = .7, width = .05, position = position_dodge(width = 0.4)) +
  geom_errorbar(aes(ymin = X1Lwr80, ymax = X1Upr80), width = 0, lwd = 1,position = position_dodge(width = 0.4)) +
  geom_point(size = 3, aes(color = Group),position = position_dodge(width = 0.4)) +
  theme_bw() +
  labs(x = 'Cluster', y = 'Max Correlation', title ='Clustering Matching Mean Max Correlations') +
  theme(panel.grid.minor = element_blank(), panel.grid.major.x = element_blank()) +
  scale_color_manual(values = c("dodgerblue", "red2")) + theme(legend.title = element_blank()) 

ggsave(filename=paste0('C:/Users/jacob.derosa/Desktop/Scripts/Baggin_Subtyping/CBCL/plots/', analysis_name, '/Clustering Matching Mean Max Correlations.png'))

```


