---
title: "Using Clusters to predict outcomes"
author: "Michelle.VanTieghem"
date: "6/18/2020"
author: "Michelle VanTieghem"
output: html_document
---


```{r, include = F, echo = F}
library(tidyverse)
library(tidymodels)
library(workflows)
library(tune)

# set seed for resamples
set.seed(100)

# load helper functions
source("helper_functions.R")

```

# Prep data for predicting Autism DX from CBCL clusters

## load data 
```{r, cache = T} 
CBCL_clust <- read.csv("../output/fullSamp_CBCL_LouClusterID+SubjID.csv")
head(CBCL_clust)
nrow(CBCL_clust)

dx_df <- read.csv("../../data/HBN_Data/Diagnosis.csv")
head(dx_df)
nrow(dx_df)
```

## prep data to model 
```{r}
# combine the clusters and outcomes, and drop rows with NAs
CBCL_dx_df <- left_join(CBCL_clust, dx_df, by = "URSI") %>%
  drop_na()  %>%
  # outcome for classification must be a factor
  mutate(Autism.Spectrum.Disorder = as.factor(Autism.Spectrum.Disorder), 
         louvain_community = as.factor(louvain_community))

nrow(CBCL_dx_df)

# check frequency of autism dx
CBCL_dx_df %>%
  count(Autism.Spectrum.Disorder)
```

## make cross-validation folds
```{r}

# use this function to set cross-validation folds, applied in all models below.
#STRATA = variables you want to stratify on. make sure cv folds are balanced

# default splits into 90% training, 10% test on each fold.
cv_folds <- vfold_cv(CBCL_dx_df, v = 10, strata = Autism.Spectrum.Disorder, breaks = 4)

cv_folds$splits[[1]]
```


## Set basic recipe: preprocessing
```{r}
# set basic recipe 
basic_recipe <- recipe(Autism.Spectrum.Disorder ~ louvain_community, 
                       data = CBCL_dx_df) %>%
  

  # one-hot encode each cluster.
  step_dummy(all_nominal(), - all_outcomes()) %>%
  #  downsample majority class( no dx) because the model doesn't do well as is.
  step_downsample(all_outcomes())


# check your resulting preprocessed data - requires extra step.
# see resulting data 
basic_recipe %>% 
  prep(training =  CBCL_dx_df) 

```


## Set model specs for classification
```{r}
# classification tree
vanilla_tree_spec <- decision_tree () %>%
  set_engine("rpart") %>%
  set_mode("classification") %>%
  # these are defaults, but we can change them
  set_args(tree_depth = 30,
           min_n = 20,  # smallest node allowed
           cost_complexity = 0.01)

# Random forest 
rf_spec <- rand_forest() %>% 
    set_engine("ranger") %>% # package for random forest 
    set_mode("classification") %>%
  set_args(mtry = 1, # predictors seen at each node of the tree... we only have one predictor! 
           # this is kind of silly ! 
            trees = 500,# trees per forest
            min_n = 20) # smallest node allowed

```

## Run classification tree
```{r}
# need to set workflow for tidymodels
wf <- workflow() %>%
  add_recipe(basic_recipe) %>%
  add_model(vanilla_tree_spec)

# take the workflow, and fit the model, with cv folds.
tree_fit <- wf %>%
  fit_resamples(
          resamples = cv_folds,
          metrics = metric_set(accuracy, roc_auc),
          control = control_resamples(save_pred = T)) 

# get metrics 
tree_metrics <- tree_fit %>%
  collect_metrics()

# get predictions
tree_predictions <- tree_fit %>%
  collect_predictions()

tree_predictions %>%
  count(.pred_class, Autism.Spectrum.Disorder)

# make a confusion matrix 
tree_predictions  %>%
  conf_mat(truth = Autism.Spectrum.Disorder, estimate = .pred_class) 

```

## Run random forest 
```{r}
# take the workflow, and use random forest model, with cv folds.
rf_fit <- wf %>%
  update_model(rf_spec) %>%
  fit_resamples(
          resamples = cv_folds,
          metrics = metric_set(accuracy, roc_auc), 
          control = control_resamples(save_pred = T))  # save predictions
# get metrics 
rf_metrics <- rf_fit %>%
  collect_metrics()

# get predictions
rf_predictions <- rf_fit %>%
  collect_predictions()

rf_predictions %>%
  count(.pred_class, Autism.Spectrum.Disorder)

# make a confusion matrix 
rf_predictions  %>%
  conf_mat(truth = Autism.Spectrum.Disorder, estimate = .pred_class) 

```



